spring:
  # Set interface timeout
  mvc:
    async:
      request-timeout: 20000
  thymeleaf:
    cache: false
  # [Optional]Upload file size limit
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  cache:
    type: redis
  data:
    # REDISDatabase configuration
    redis:
      # [Must be modified] RedisServer IP, REDIS is installed on this machine, use127.0.0.1
      host: 127.0.0.1
      # [Must be modified] port number
      port: 6379
      # [Optional] database DB
      database: 7
      # [Optional] Access password. If your redis server does not have a password set, you do not need to use a password to connect.
      password: luna
      # [Optional] timeout
      timeout: 10000
  # mysqldata source
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wvp273Database integration?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  # H2 Database
  #  datasource:
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:wvp
  #    username: sa
  #    password: 12345678
  #    sql:
  #      init:
  #        # Only initialize built-in database when starting, such as h2:mem
  #        mode: embedded
  #        schema-locations: file:database/2.7.4-h2/h2-schema.sql
  #        data-locations: file:database/2.7.4-h2/h2-data.sql
  #  # H2 database console, please note it should only be used in testing environments!
  #  h2:
  #    console:
  #      enabled: true
#[Optional] WVPThe listening HTTP port, web pages and interface calls are all on this port
server:
  port: 18080
  # [Optional] HTTPSConfiguration, not enabled by default
  ssl:
    # [Optional] Whether to enable HTTPS access
    enabled: false
    # [Optional] Certificate file path, placed inresource/Just go to the directory and change xxx to the file name.
    key-store: classpath:test.monitor.89iot.cn.jks
    # [Optional] Certificate password
    key-store-password: gpf64qmw
    # [Optional] Certificate type, default is jks, modify according to actual situation
    key-store-type: JKS

# Configuration as 28181 server
sip:
  # [Optional] 28181The port the service listens on
  port: 8116
  # According to the provisions of national standard 6.1.2, domain should use the first ten digits of the unified ID code. Appendix D of the national standard defines the first 8 digits as the center code (composed of provincial, municipal, district and grassroots numbers, refer toGB/T 2260-2007）
  # The last two digits are industry codes. For definitions, please refer to the appendix.D.3
  # 3701020049Identification of information industry access in Lixia District, Jinan, Shandong Province
  # [Optional]
  domain: 4101050000
  # [Optional]
  id: 41010500002000000001
  # [Optional] Public authentication password. If you remove the password, you will have to add the device in advance to pass the authentication.
  password: 12345678
  # Whether to store alarm information
  alarm: false

#zlm Default server configuration
media:
  id: zlmediakit-local
  # [Must be modified] zlmServer's intranetIP
  ip: 192.168.1.10
  # [Must be modified] zlmServer'shttp.port
  http-port: 9092
  # [Required] zlmServer'shook.admin_params=secret
  secret: TWSYFgYJOQWB4ftgeYut8DW4wbs7pQnj
  # Enable multi-port mode. Multi-port mode uses ports to distinguish each flow for better compatibility. Single port uses the ssrc of the flow to distinguish. For on-demand timeout, it is recommended to use multi-port testing.
  rtp:
    # [Optional] Whether to enable multi-port mode. When enabled, the port will be selected within the portRange range for media streaming.
    enable: true
    # [Optional] Select a port within this range for media streaming. This attribute must be configured on zlm in advance, otherwise the automatic configuration of this attribute may not be successful.
    port-range: 40000,45000 # port range
    # [Optional] National standard cascade selects ports within this range to send media streams,
    send-port-range: 50000,55000 # port range
# [Configure according to business needs]
user-settings:
  # on demand/Video playback waiting timeout, unit: milliseconds
  play-timeout: 180000
  # [Optional] Multiport mode uses random SSRC, SSRC is allowed to be repeated (defaultfalse）
  ssrc-random: false
  # [Optional] Automatically play on demand. When using a fixed stream address for playback, if the playback is not on demand, it will automatically play on demand. Requiredrtp.enable=true
  auto-apply-play: true
  # Whether to record live push streaming
  record-push-live: true
  # Is the national standard recorded?
  record-sip: true
  # National standard on-demand streaming on demand, true: someone is watching the stream, no one is watching it, it is released, false: it is not automatically released after it is pulled up.
  stream-on-demand: true
  # Whether to return the Date attribute, true: not returned, to prevent the camera from automatically adjusting the time through this parameter, false: returned, the camera may adjust the time based on this time
  disable-date-header: false
  # The maximum number of entries to be retained in the device registration time list. The default is 100. If set to 0, there is no limit.
  device-register-time-max-count: 100
  # Device registration time list expiration time (hours), default 3, set to 0 to never expire
  device-register-time-ttl-hours: 3
  # The maximum number of entries in the device heartbeat time list, the default is 100, if set to 0 there is no limit
  device-keepalive-time-max-count: 100
  # Device heartbeat time list expiration time (hours), default 1, set to 0 to never expire
  device-keepalive-time-ttl-hours: 1

