spring:
    # Upload file size limit
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
    cache:
        type: redis
    data:
        # REDISDatabase configuration
        redis:
            # [Must be modified] RedisServer IP, REDIS is installed on this machine, use127.0.0.1
            host: ${REDIS_HOST:127.0.0.1}
            # [Must be modified] port number
            port: ${REDIS_PORT:6379}
            # [Optional] database DB
            database: ${REDIS_DB:6}
            # [Optional] Access password. If your redis server does not have a password set, you do not need to use a password to connect.
            password: ${REDIS_PWD:root}
            # [Optional] timeout
            timeout: 10000
    # [Required] jdbcDatabase configuration
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/wvp2?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
        username: root
        password: root123
# [Optional] WVPThe listening HTTP port, web pages and interface calls are all on this port
server:
    port: 18080

# Configuration as 28181 server
sip:
    # [Must be modified] The IP of this machine corresponds to your network card. The IP you monitor depends on the network card you use.，
    # If you want to monitor multiple network cards, you can use commas to separate multiple IPs, for example： 192.168.1.4,10.0.0.4
    # If you don’t understand, just use 0.0.0.0, which is fine in most cases.
    # Please do not use 127.0.0.1, any domain name including localhost is not allowed。
    ip: ${WVP_HOST:127.0.0.1}
    # [Optional] 28181The port the service listens on
    port: ${WVP_PORT:5060}
    # According to the provisions of national standard 6.1.2, domain should use the first ten digits of the unified ID code. Appendix D of the national standard defines the first 8 digits as the center code (composed of provincial, municipal, district and grassroots numbers, refer toGB/T 2260-2007）
    # The last two digits are industry codes. For definitions, please refer to the appendix.D.3
    # 3701020049Identification of information industry access in Lixia District, Jinan, Shandong Province
    # [Optional]
    domain: ${WVP_DOMAIN:4401020049}
    # [Optional]
    id: ${WVP_ID:44010200492000000001}
    # [Optional] Public authentication password. If you remove the password, you will have to add the device in advance to pass the authentication.
    password: ${WVP_PWD:admin123}

#zlm Default server configuration
media:
    # [Must be modified] zlmThe unique ID of the server, used to distinguish which server it is when triggering the hook.,general.mediaServerId
    id:
    # [Must be modified] zlmServer's intranetIP
    ip: ${ZLM_HOST:127.0.0.1}
    # [Must be modified] zlmServer'shttp.port
    http-port: ${ZLM_PORT:80}
    # [Optional] zlmServer'shook.admin_params=secret
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
    # Enable multi-port mode. Multi-port mode uses ports to distinguish each flow for better compatibility. Single port uses the ssrc of the flow to distinguish. For on-demand timeout, it is recommended to use multi-port testing.
    rtp:
        # [Optional] Whether to enable multi-port mode. When enabled, the port will be selected within the portRange range for media streaming.
        enable: true
        # [Optional] Select ports within this range for media streaming,
        port-range: 30000,30500 # port range
        # [Optional] National standard cascade selects ports within this range to send media streams,
        send-port-range: 30000,30500 # port range
    # Video auxiliary service. Deploying this service can realize the management and download of zlm video. 0 means not to use it.
    record-assist-port: 18081
    sdp-ip: ${sip.ip}
    stream-ip: ${sip.ip}

# [Configure according to business needs]
user-settings:
    # Whether to record live push streaming
    record-push-live: true
    auto-apply-play: true
    # The maximum number of entries to be retained in the device registration time list. The default is 100. If set to 0, there is no limit.
    device-register-time-max-count: 100
    # Device registration time list expiration time (hours), default 3, set to 0 to never expire
    device-register-time-ttl-hours: 3
    # The maximum number of entries in the device heartbeat time list, the default is 100, if set to 0 there is no limit
    device-keepalive-time-max-count: 100
    # Device heartbeat time list expiration time (hours), default 1, set to 0 to never expire
    device-keepalive-time-ttl-hours: 1
