version: "3"
services:
  polaris-redis:
    image: redis:latest # Use the official Redis image
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - media-net
    # ports:
    #   - 6379:6379
    volumes:
      - ./redis/conf/redis.conf:/opt/polaris/redis/redis.conf
      - ./volumes/redis/data/:/data
    environment:
      TZ: "Asia/Shanghai"
    command: redis-server /opt/polaris/redis/redis.conf --appendonly yes

  polaris-mysql:
    image: mysql:8 # Use the official MySQL 8 image
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -proot"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 15s
    networks:
      - media-net
    environment:
      MYSQL_DATABASE: wvp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wvp_user
      MYSQL_PASSWORD: wvp_password
      TZ: Asia/Shanghai
    # ports:
    #   - 3306:3306
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./logs/mysql:/logs
      - ./volumes/mysql/data:/var/lib/mysql
      - ../database/2.7.4/init-mysql-2.7.4.sql:/docker-entrypoint-initdb.d/init.sql # Initialization SQL script directory
    command: [
        # '--default-authentication-plugin=mysql_native_password',
        "--innodb-buffer-pool-size=80M",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
        "--default-time-zone=+8:00",
        "--lower-case-table-names=1",
      ]

  polaris-media:
    image: zlmediakit/zlmediakit:master # Replace with official image
    restart: always
    networks:
      - media-net
    ports:
      - "${MediaRtmp:-10935}:${MediaRtmp:-10935}/tcp"     # [collect flow]RTMP
      - "${MediaRtmp:-10935}:${MediaRtmp:-10935}/udp"     # [collect flow]RTMP
      - "${MediaRtsp:-5540}:${MediaRtsp:-5540}/tcp"       # [collect flow]RTSP
      - "${MediaRtsp:-5540}:${MediaRtsp:-5540}/udp"       # [collect flow]RTSP
      - "${MediaRtp:-10000}:${MediaRtp:-10000}/tcp"       # [collect flow]RTP
      - "${MediaRtp:-10000}:${MediaRtp:-10000}/udp"       # [collect flow]RTP
    volumes:
      - ./volumes/video:/opt/media/bin/www/record/
      - ./logs/media:/opt/media/log/
      - ./media/config.ini:/conf/config.ini
    command: ["MediaServer", "-c", "/conf/config.ini", "-l", "0"]

  polaris-wvp:
    # Explicitly specify the build context and Dockerfile path
    build:
      context: .. # The root path of the build context
      dockerfile: ./docker/wvp/Dockerfile # Dockerfile location relative to context path
    restart: always
    networks:
      - media-net
    ports:
      - "18978:18978"
      - "${SIP_Port:-8116}:${SIP_Port:-8116}/udp"
      - "${SIP_Port:-8116}:${SIP_Port:-8116}/tcp"
    depends_on:
      polaris-redis:
        condition: service_healthy
      polaris-mysql:
        condition: service_healthy
      polaris-media:
        condition: service_started
    volumes:
      - ./wvp/config:/opt/wvp/config
      - ./wvp/wvp/:/opt/ylcx/wvp/
      - ./logs/wvp:/opt/wvp/logs/
    environment:
      TZ: "Asia/Shanghai"
      # docker env
      RUN_ENV: "docker"
      # stream linkedIP
      Stream_IP: ${Stream_IP}
      # SDPinsideIP
      SDP_IP: ${SDP_IP}
      # [Optional] zlmThe IP used by the server to access WVP. The default is 127.0.0.1. This must be configured when zlm and wvp are not deployed on the same server.
      ZLM_HOOK_HOST: polaris-wvp
      ZLM_HOST: polaris-media
      ZLM_SERCERT: su6TiedN2rVAmBbIDX0aa0QTiBJLBdcf

      MediaHttp: ${WebHttp:-8080}
      #MediaHttps: ${WebHttps:-8081}
      MediaRtmp: ${MediaRtmp:-10935}
      MediaRtsp: ${MediaRtsp:-5540}
      MediaRtp: ${MediaRtp:-10000}

      REDIS_HOST: polaris-redis
      REDIS_PORT: 6379

      DATABASE_HOST: polaris-mysql
      DATABASE_PORT: 3306
      DATABASE_USER: wvp_user
      DATABASE_PASSWORD: wvp_password

      SIP_ShowIP: ${SIP_ShowIP}
      SIP_Port: ${SIP_Port:-8116}
      SIP_Domain: ${SIP_Domain}
      SIP_Id: ${SIP_Id}
      SIP_Password: ${SIP_Password}

      RecordSip: ${RecordSip}
      RecordPushLive: ${RecordPushLive}

  polaris-nginx:
    # Explicitly specify the build context and Dockerfile path
    build:
      context: .. # The root path of the build context
      dockerfile: ./docker/nginx/Dockerfile # Dockerfile location relative to context path
    ports:
      - "${WebHttp:-8080}:8080"
    depends_on:
      - polaris-wvp
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - ./logs/nginx:/var/log/nginx
    environment:
      # stream linkedIP
      Stream_IP: ${Stream_IP}
    networks:
      - media-net

networks:
  media-net:
    driver: bridge
