spring:
    cache:
        type: redis
    thymeleaf:
        cache: false
    # Set interface timeout
    mvc:
        async:
            request-timeout: 20000
    # [Optional]Upload file size limit
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
    data:
      # REDISDatabase configuration
      redis:
          # [Must be modified] RedisServer IP, REDIS is installed on this machine, use127.0.0.1
          host: ${REDIS_HOST:127.0.0.1}
          # [Must be modified] port number
          port: ${REDIS_PORT:6379}
          # [Optional] database DB
          database: 1
          # [Optional] Access password. If your redis server does not have a password set, you do not need to use a password to connect.
          password:
          # [Optional] timeout
          timeout: 10000
         ## [Optional] The maximum number of jedis instances that can be allocated to a pool
         #poolMaxTotal: 1000
         ## [Optional] The maximum number of states a pool can have isidle(free)jedis instance
         #poolMaxIdle: 500
         ## [Optional] maximum waiting time(seconds)
         #poolMaxWait: 5
    # [Required] jdbcDatabase configuration
    datasource:
        # mysqldata source
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DATABASE_HOST:127.0.0.1}:${DATABASE_PORT:3306}/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
        username: ${DATABASE_USER:root}
        password: ${DATABASE_PASSWORD:root}

#[Optional] The listening HTTP port, web pages and interface calls are all on this port
server:
    port: 18978
    ssl:
        # [Optional] Whether to enable HTTPS access
        # dockerRun inside, not needed internallyHTTPS
        enabled: false
# Configuration as 28181 server
sip:
    # [Must be modified] The IP of this machine corresponds to your network card. The IP you monitor depends on the network card you use.，
    # If you want to monitor multiple network cards, you can use commas to separate multiple IPs, for example： 192.168.1.4,10.0.0.4
    # If you don’t understand, just use 0.0.0.0, which is fine in most cases.
    # Please do not use 127.0.0.1, any domain name including localhost is not allowed。
    ip: 0.0.0.0
    # [Optional] There is no business requirement. It is only used for front-end display.
    show-ip: ${SIP_ShowIP}
    # [Optional]
    port: ${SIP_Port:8116}
    # According to the provisions of national standard 6.1.2, domain should use the first ten digits of the unified ID code. Appendix D of the national standard defines the first 8 digits as the center code (composed of provincial, municipal, district and grassroots numbers, refer toGB/T 2260-2007）
    # The last two digits are industry codes. For definitions, please refer to the appendix.D.3
    # 3701020049Identification of information industry access in Lixia District, Jinan, Shandong Province
    # [Optional]
    domain: ${SIP_Domain:3402000000}
    # [Optional]
    id: ${SIP_Id:34020000002000000001}
    # [Optional] The default device authentication password. Subsequent extensions will use a device-specific password. If the password is removed, verification will not be performed.
    password: ${SIP_Password}
    # [Optional] If the national standard cascade registration fails, the time interval for re-initiating registration. Default 60 seconds
    register-time-interval: 60
    # [Optional] PTZ control speed
    ptz-speed: 50
    # TODO [Optional] It will automatically go online after receiving the heartbeat. After restarting the service, all devices will be set offline. The default is false and will go online after registration. Set to true to receive a heartbeat and set it to go online.。
    # keepalliveToOnline: false
    # Whether to store alarm information
    alarm: true
    # Timeout for command sending and waiting for reply, unit: milliseconds
    timeout: 1000

# Default server configuration
media:
  id: polaris
  # [Must be modified] ZLM Intranet IP and port
  ip: ${ZLM_HOST:127.0.0.1}
  http-port: 80
  # [Optional] IP when returning the flow address, leave it blank and use it media.ip
  stream-ip: ${Stream_IP}
  # [Optional] wvpThe IP used in national standard signaling. This IP is the IP that the camera can access. Leave it blank. media.ip
  sdp-ip: ${SDP_IP}
  # [Optional] zlmThe IP used by the server to access WVP. The default is 127.0.0.1. This must be configured when zlm and wvp are not deployed on the same server.
  hook-ip: ${ZLM_HOOK_HOST}
  # [Optional] sslport
  http-ssl-port: 0
  flv-port: ${MediaHttp:}
  flv-ssl-port: ${MediaHttps:}
  ws-flv-port: ${MediaHttp:}
  ws-flv-ssl-port: ${MediaHttps:}
  rtp-proxy-port: ${MediaRtp:}
  rtmp-port: ${MediaRtmp:}
  rtmp-ssl-port: 0
  rtsp-port: ${MediaRtsp:}
  rtsp-ssl-port: 0
  # [Optional] Whether to automatically configure ZLM. If you want to configure ZLM manually, you can set it to false. It is not recommended for new users to modify it.
  auto-config: true
  # [Optional] 
  secret: ${ZLM_SERCERT}
  # Enable multi-port mode. Multi-port mode uses ports to distinguish each flow for better compatibility. Single port uses the ssrc of the flow to distinguish. For on-demand timeout, it is recommended to use multi-port testing.
  rtp:
    # [Optional] Whether to enable multi-port mode. When enabled, the port will be selected within the portRange range for media streaming.
    enable: false
    # [Optional] 
    port-range: 30000,30500 
    # [Optional] 
    send-port-range: 50502,50506 

  record-path: /opt/media/bin/www/record/
  record-day: 7
  record-assist-port: 0
user-settings:
    auto-apply-play: true
    play-timeout: 30000
    wait-track: false
    record-push-live: ${RecordPushLive:false}
    record-sip: ${RecordSip:false}
    stream-on-demand: true
    interface-authentication: true
    broadcast-for-platform: TCP-PASSIVE
    push-stream-after-ack: true
    send-to-platforms-when-id-lost: true
    interface-authentication-excludes:
    #  - /api/**
    push-authority: true
    # allowed-origins:
    #   - http://localhost:8080
    #   - http://127.0.0.1:8080
    #   - http://0.0.0.0:8080
    #   - ${NGINX_HOST}
    jwkFile: classpath:xxxxxxxxxxx.json
logging:
  config: classpath:logback-spring.xml

