spring:
  # Set interface timeout
  mvc:
    async:
      request-timeout: 20000
  thymeleaf:
    cache: false
  # [Optional]Upload file size limit
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    # REDISDatabase configuration
    redis:
      # [Must be modified] RedisServer IP, REDIS is installed on this machine, use127.0.0.1
      host: 127.0.0.1
      # [Must be modified] port number
      port: 6379
      # [Optional] database DB
      database: 1
      # [Optional] Access password. If your redis server does not have a password set, you do not need to use a password to connect.
      password:
      # [Optional] timeout
      timeout: 30000
  # mysqldata source
  datasource:
    dynamic:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
      username: root
      password: root
#[Optional] The listening HTTP port, web pages and interface calls are all on this port
server:
  port: 18978
  ssl:
    # [Optional] Whether to enable HTTPS access
    enabled: false
# Configuration as 28181 server
sip:
  # [Must be modified] nativeIP
  ip: 127.0.0.1
  # [Optional]
  port: 8116
  # [Optional]
  domain: 3402000000
  # [Optional]
  id: 34020000002000000001
  password:
  alarm: true

# Default server configuration
media:
  id: polaris
  # [Must be modified]IntranetIP
  ip: 127.0.0.1
  http-port: 6080
  # [Optional] IP when returning the flow address, leave it blank and use it media.ip
  stream-ip: 127.0.0.1
  # [Optional] wvpThe IP used in national standard signaling. This IP is the IP that the camera can access. Leave it blank. media.ip
  sdp-ip: 127.0.0.1
  # [Optional] Hook IP, Used by defaultsip.ip
  hook-ip: 127.0.0.1
  # [Optional] sslport
  http-ssl-port: 4443
  rtp-proxy-port: 10000
  rtmp-port: 10935
  rtmp-ssl-port: 41935
  rtsp-port: 5540
  rtsp-ssl-port: 45540
  # [Optional] 
  secret: su6TiedN2rVAmBbIDX0aa0QTiBJLBdcf
  # Enable multi-port mode. Multi-port mode uses ports to distinguish each flow for better compatibility. Single port uses the ssrc of the flow to distinguish. For on-demand timeout, it is recommended to use multi-port testing.
  rtp:
    # [Optional] Whether to enable multi-port mode. When enabled, the port will be selected within the portRange range for media streaming.
    enable: false
    # [Optional] 
    port-range: 30000,30500 
    # [Optional] 
    send-port-range: 50502,50506 

  record-path: /opt/media/record
  record-day: 7
  record-assist-port: 0
user-settings:
    auto-apply-play: true
    play-timeout: 30000
    wait-track: false
    record-push-live: false
    record-sip: false
    stream-on-demand: true
    interface-authentication: false
    broadcast-for-platform: TCP-PASSIVE
    push-stream-after-ack: true
    send-to-platforms-when-id-lost: true
    interface-authentication-excludes:
      - /api/**
    push-authority: false
    allowed-origins:
      - http://localhost:8080
      - http://127.0.0.1:8080
      - http://0.0.0.0:8080
logging:
  config: classpath:logback-spring.xml

